[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  PRISMA_CLI_BINARY_TARGETS = "rhel-openssl-3.0.x,debian-openssl-3.0.x,linux-musl-openssl-3.0.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Disable caching for auth routes
[[headers]]
  for = "/api/auth/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
  for = "/login"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
